### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by mishoboss** [feathersjs/feathers-batch#18] opened 2016-08-19 09:19 UTC
Hello, I'm not getting any response to batch calls.

This is sent:
`["batch::create",{"type":"series","call":[["pages::create",{"text":0}],["pages::create",{"text":1}],["pages::create",{"text":2}],["pages::create",{"text":3}]]},{}]`

No response!  :(

I've put this to server app:

```
.use('/batch', batcher({
      limit: 10
    }))
```

**Comment by daffl** [comment] 2016-09-01 02:17
Can you post your full setup? I can't seem to reproduce with a basic setup.

**Comment by ekryski** [comment] 2016-10-16 05:05
Since it's been over a month I'm going to close this. @mishoboss if you are still having this issue and want to post more info we are happy to revisit.

**Closed by ekryski** 2016-10-16 05:05 UTC
